language: ruby
rvm:
- 2.7.0

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
 - gem install jekyll html-proofer jekyll-sitemap

before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild

branches:
  only:
  - master


sudo: false
